# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideorder',
            name='place',
        ),
        migrations.RemoveField(
            model_name='rideorder',
            name='time',
        ),
        migrations.AddField(
            model_name='rideorder',
            name='current_location_lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideorder',
            name='current_location_lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideorder',
            name='current_location_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideorder',
            name='target_location_lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideorder',
            name='target_location_lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rideorder',
            name='target_location_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('directed', 'Directed')], max_length=30),
        ),
    ]
