# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180726_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideorder',
            name='day_chosen',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='day_chosen2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='direction_option',
            field=models.CharField(choices=[('ROUNDTRIP', 'Roundtrip'), ('ONEWAY', 'Oneway')], default='ROUNDTRIP', max_length=30),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='payment_option',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='time_chosen',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='time_chosen2',
            field=models.TextField(default=''),
        ),
    ]
