# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180731_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideorder',
            name='payment_option',
            field=models.CharField(choices=[('CHILD', 'Child'), ('SUBSIDISED', 'Subsidised'), ('REGULAR', 'Regular')], default='CHILD', max_length=30),
        ),
    ]
