# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180731_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideorder',
            name='current_location_lat',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='current_location_lng',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='day_chosen',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='day_chosen2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='direction_option',
            field=models.CharField(blank=True, choices=[('ROUNDTRIP', 'Roundtrip'), ('ONEWAY', 'Oneway')], default='ROUNDTRIP', max_length=30),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('CHILD', 'Child'), ('SUBSIDISED', 'Subsidised'), ('REGULAR', 'Regular')], default='CHILD', max_length=30),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='target_location_lat',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='target_location_lng',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='time_chosen',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='time_chosen2',
            field=models.TextField(blank=True, default=''),
        ),
    ]
