# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180731_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideorder',
            name='current_location_lat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='current_location_lng',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='target_location_lat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='target_location_lng',
            field=models.TextField(blank=True, default=''),
        ),
    ]
