# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180731_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='samplesheet',
            field=models.FileField(blank=True, default='', upload_to=b''),
        ),
    ]
