# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180731_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('DIRECTED', 'Directed')], max_length=30),
        ),
    ]
