# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180731_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='attachments',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
