# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-28 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180809_0603'),
        ('app', '0014_auto_20180814_0808'),
    ]

    operations = [
    ]
