# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20180828_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideorder',
            name='second_current_location_lat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='second_current_location_lng',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='second_current_location_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='second_target_location_lat',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='second_target_location_lng',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='second_target_location_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
