# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-03 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20180815_1502'),
        ('app', '0016_auto_20180831_1608'),
    ]

    operations = [
    ]
