import LocalizedStrings from 'localized-strings';

let strings = new LocalizedStrings({
    en: {
        welcome: "Welcome",
        askForRide: "Ask for Ride",
        rideDescription: "In our municipality we have ride sharing service that arranges one-time shared rides on very short notice.",
        more: "More",
        less: "Less",
        reportAnIssue: "Report an Issue",
        issueDescription: "If you see an issue, make a picture and send us. We appreciate your help! We probably won't be able to send you an individual response, but we'll investigate your report and use the information you provide.",
        order: "Order",
        orders: "Orders",
        child: "Child",
        subsidised: "Subsidised",
        regular: "Regular",
        estonia: "Estonia",
        targetLocation: "Target location",
        confirmCurrentTarget: "Confirm current location and target",
        issue: "Issue",
        issues: "Issues",
        sampleIssue: "Sample issue",
        address: "Address:",
        addNewAspect: "Add new aspect",
        history: "History",
        from: "From",
        to: "To",
        dateTime: "Date & Time",
        paymentOption: "Payment Option",
        rideType: "Ride Type",
        roundTrip: "Round trip",
        oneWay: "One way",
        status: "Status",
        directed: "Directed",
        new: "New",
        ourMunicipality: "Our Municipality",
        searchDatabase: "Search in database",
        rideOrders: "Ride Orders",
        items: "items",
        sortedByName: "Sorted by Name",
        newOrder: "New Order",
        newIssue: "New Issue",
        name: "Name",
        place: "Place",
        oneWayOrRoundtrip: "One way / Roundtrip",
        reporter: "Reporter"
    },
    et: {
        welcome: "Tere tulemast!",
        askForRide: "Telli",
        rideDescription: "Meie vallas on ühistransport ka jagamisteenusena, lühikese etteteatamisajaga",
        more: "näita rohkem",
        less: "näita vähem",
        reportAnIssue: "Anna tagasisidet",
        issueDescription: "Kui näed midagi, mida saaks paremini, võid teha pildi ja saata meile. Me ei pruugi saada isiklikult vastata, kuid me uurime asja ja püüame meie võimuses olevat parandada. Aitäh abi eest!",
        order: "Telli",
        orders: "Tellimused",
        child: "Laps",
        subsidised: "Toetusega sõitja",
        regular: "Tavasõitja",
        estonia: "Eesti",
        targetLocation: "Sihtkoht",
        confirmCurrentTarget: "Kinnita lähtekoht ja sihtkoht",
        issue: "Tagasiside",
        issues: "Tagasiside",
        sampleIssue: "näide",
        address: "Aadress:",
        addNewAspect: "Lisa",
        history: "Tellimuste ajalugu",
        from: "Lähtekoht",
        to: "Sihtkoht",
        dateTime: "Kuupäev ja kellaaeg",
        paymentOption: "Makseviis",
        rideType: "Sõidutüüp",
        roundTrip: "edasi-tagasi",
        oneWay: "üks suund",
        status: "Olek",
        directed: "Edastatud juhile",
        new: "uus",
        ourMunicipality: "Meie vald",
        searchDatabase: "Otsi andmebaasist",
        rideOrders: "Tellimused",
        items: "teemat",
        sortedByName: "Järjestatud nime järgi",
        newOrder: "Uus tellimus",
        name: "Nimi",
        place: "Koht",
        oneWayOrRoundtrip: "Üks suund / Edasi-tagasi",
        reporter: "Teataja"
    },
    est: {
        welcome: "Tere tulemast!",
        askForRide: "Telli",
        rideDescription: "Meie vallas on ühistransport ka jagamisteenusena, lühikese etteteatamisajaga",
        more: "näita rohkem",
        less: "näita vähem",
        reportAnIssue: "Anna tagasisidet",
        issueDescription: "Kui näed midagi, mida saaks paremini, võid teha pildi ja saata meile. Me ei pruugi saada isiklikult vastata, kuid me uurime asja ja püüame meie võimuses olevat parandada. Aitäh abi eest!",
        order: "Telli",
        orders: "Tellimused",
        child: "Laps",
        subsidised: "Toetusega sõitja",
        regular: "Tavasõitja",
        estonia: "Eesti",
        targetLocation: "Sihtkoht",
        confirmCurrentTarget: "Kinnita lähtekoht ja sihtkoht",
        issue: "Tagasiside",
        issues: "Tagasiside",
        sampleIssue: "näide",
        address: "Aadress:",
        addNewAspect: "Lisa",
        history: "Tellimuste ajalugu",
        from: "Lähtekoht",
        to: "Sihtkoht",
        dateTime: "Kuupäev ja kellaaeg",
        paymentOption: "Makseviis",
        rideType: "Sõidutüüp",
        roundTrip: "edasi-tagasi",
        oneWay: "üks suund",
        status: "Olek",
        directed: "Edastatud juhile",
        new: "uus",
        ourMunicipality: "Meie vald",
        searchDatabase: "Otsi andmebaasist",
        rideOrders: "Tellimused",
        items: "teemat",
        sortedByName: "Järjestatud nime järgi",
        newOrder: "Uus tellimus",
        name: "Nimi",
        place: "Koht",
        oneWayOrRoundtrip: "Üks suund / Edasi-tagasi",
        reporter: "Teataja"
    },
    eesti: {
        welcome: "Tere tulemast!",
        askForRide: "Telli",
        rideDescription: "Meie vallas on ühistransport ka jagamisteenusena, lühikese etteteatamisajaga",
        more: "näita rohkem",
        less: "näita vähem",
        reportAnIssue: "Anna tagasisidet",
        issueDescription: "Kui näed midagi, mida saaks paremini, võid teha pildi ja saata meile. Me ei pruugi saada isiklikult vastata, kuid me uurime asja ja püüame meie võimuses olevat parandada. Aitäh abi eest!",
        order: "Telli",
        orders: "Tellimused",
        child: "Laps",
        subsidised: "Toetusega sõitja",
        regular: "Tavasõitja",
        estonia: "Eesti",
        targetLocation: "Sihtkoht",
        confirmCurrentTarget: "Kinnita lähtekoht ja sihtkoht",
        issue: "Tagasiside",
        issues: "Tagasiside",
        sampleIssue: "näide",
        address: "Aadress:",
        addNewAspect: "Lisa",
        history: "Tellimuste ajalugu",
        from: "Lähtekoht",
        to: "Sihtkoht",
        dateTime: "Kuupäev ja kellaaeg",
        paymentOption: "Makseviis",
        rideType: "Sõidutüüp",
        roundTrip: "edasi-tagasi",
        oneWay: "üks suund",
        status: "Olek",
        directed: "Edastatud juhile",
        new: "uus",
        ourMunicipality: "Meie vald",
        searchDatabase: "Otsi andmebaasist",
        rideOrders: "Tellimused",
        items: "teemat",
        sortedByName: "Järjestatud nime järgi",
        newOrder: "Uus tellimus",
        name: "Nimi",
        place: "Koht",
        oneWayOrRoundtrip: "Üks suund / Edasi-tagasi",
        reporter: "Teataja"
    }
});

export default strings;