import LocalizedStrings from 'localized-strings';

let strings = new LocalizedStrings({
    en: {
        welcome: "Welcome",
        askForRide: "Ask for Ride",
        rideDescription: "In our municipality we have ride sharing service that arranges one-time shared rides on very short notice.",
        more: "More",
        less: "Less",
        reportAnIssue: "Report an Issue",
        issueDescriptionLabel: "If you see an issue, make a picture and send us. We appreciate your help! We probably won't be able to send you an individual response, but we'll investigate your report and use the information you provide.",
        orderList: "Order List",
        issueList: "Issue List",
        order: "Order",
        orders: "Orders",
        child: "Child",
        childTransport: "Child Transport",
        subsidised: "Subsidised",
        regular: "Regular",
        estonia: "Estonia",
        targetLocation: "Target location",
        confirmCurrentTarget: "Confirm current location and target",
        issue: "Issue",
        issues: "Issues",
        sampleIssue: "Sample issue",
        address: "Address:",
        addNewAspect: "Add new aspect",
        history: "History",
        findATopic: "Find a topic",
        from: "From",
        to: "To",
        dateTime: "Date & Time",
        paymentOption: "Payment Option",
        rideType: "Ride Type",
        roundTrip: "Round trip",
        oneWay: "One way",
        status: "Status",
        directed: "Directed",
        new: "New",
        ourMunicipality: "Our Municipality",
        searchDatabase: "Search in database",
        rideOrders: "Ride Orders",
        items: "items",
        sortedByName: "Sorted by Name",
        newOrder: "New Order",
        newIssue: "New Issue",
        name: "Name",
        place: "Place",
        oneWayOrRoundtrip: "One way / Roundtrip",
        reporter: "Reporter",
        confirming: 'Confirming...',
        confirmOrder: 'Confirm Order',
        change: 'Change',
        cancel: 'Cancel',
        day: 'Day',
        time: 'Time',
        timePickerCaption: 'Time',
        processingAddress: 'Processing address',
        transport: 'Transport',
        action: 'Action',
        deleteOrder: 'Are you sure you want to delete this order? This can\'t be undone.',
        attachments: 'Attachments',
        dateSubmitted: 'Date Submitted',
        issueDescription: 'Issue Description',
        addressOfTheIssue: 'Address of the issue',
        addPicture: 'Add picture',
        sendToUs: 'Send to us',
        discard: 'Discard',
        fromLocation: 'From location',
        direction: 'Direction',
        enterName: 'Enter name',
        enterDate: 'Enter date',
        enterTime: 'Enter time',
        saveRideOrder: 'Save Ride Order',
        saving: 'Saving...',
        inProgress: 'In Progress',
        enterIssueDescription: 'Enter issue description',
        enterIssueAddress: 'Enter issue address',
        enterIssueReporter: 'Enter issue reporter',
        submitIssue: 'Submit Issue',
        successfullyUpdatedRideOrder: 'Successfully updated ride order.',
        successfullyCreatedANewRideOrder: 'Successfully created a new ride order.',
        orderReceived: 'Your order is well received',
        confirmationWillReceive: 'Confirmation will arrive to your mail',
        placeNotFound: 'Place not found.'
    },
    et: {
        welcome: "Tere tulemast!",
        askForRide: "Telli",
        rideDescription: "Meie vallas on ühistransport ka jagamisteenusena, lühikese etteteatamisajaga",
        more: "näita rohkem",
        less: "näita vähem",
        reportAnIssue: "Anna tagasisidet",
        issueDescriptionLabel: "Kui näed midagi, mida saaks paremini, võid teha pildi ja saata meile. Me ei pruugi saada isiklikult vastata, kuid me uurime asja ja püüame meie võimuses olevat parandada. Aitäh abi eest!",
        orderList: "Tellimuste ajalugu",
        issueList: "Tagasiside ajalugu",
        order: "Telli",
        orders: "Tellimused",
        child: "Laps",
        childTransport: "Lapse sõit",
        regularTransport: "Tavasõit",
        subsidisedTransport: "Toetusega sõit",
        subsidised: "Toetusega sõitja",
        regular: "Tavasõitja",
        estonia: "Eesti",
        targetLocation: "Sihtkoht",
        confirmCurrentTarget: "Kinnita lähtekoht ja sihtkoht",
        issue: "Tagasiside",
        issues: "Tagasiside",
        sampleIssue: "näide",
        address: "Aadress:",
        addNewAspect: "Lisa",
        history: "Ajalugu",
        findATopic: "otsi",
        from: "Lähtekoht",
        to: "Sihtkoht",
        dateTime: "Kuupäev ja kellaaeg",
        paymentOption: "Makseviis",
        rideType: "Sõidu tüüp",
        roundTrip: "edasi-tagasi",
        oneWay: "üks suund",
        status: "Olek",
        directed: "Edastatud juhile",
        new: "uus",
        ourMunicipality: "Meie vald",
        searchDatabase: "Otsi andmebaasist",
        rideOrders: "Tellimused",
        items: "teemat",
        sortedByName: "Järjestatud nime järgi",
        newOrder: "Uus tellimus",
        name: "Nimi",
        place: "Koht",
        oneWayOrRoundtrip: "Üks suund / Edasi-tagasi",
        reporter: "Teataja",
        confirming: 'Kinnitus...',
        confirmOrder: 'Kinnita tellimus',
        change: 'Muuda',
        cancel: 'Tühista',
        day: 'Päev',
        time: 'Aeg',
        timePickerCaption: 'Kellaaeg',
        processingAddress: 'Otsin aadressi',
        transport: 'Transport',
        action: 'Tegevus',
        deleteOrder: 'Kas soovid tellimuse tühistada?',
        attachments: 'Lisad',
        dateSubmitted: 'Esitamise kuupäev',
        issueDescription: 'Tagasiside sisu',
        addressOfTheIssue: 'Sisesta aadress',
        addPicture: 'Lisa pilt',
        sendToUs: 'Saada',
        discard: 'Loobu',
        fromLocation: 'Lähtekoht',
        direction: 'Suund',
        enterName: 'Sisesta nimi ',
        enterDate: 'Sisesta kuupäev',
        enterTime: 'Sisesta aeg',
        saveRideOrder: 'Salvesta tellimus',
        saving: 'Salvestab...',
        inProgress: 'käimasolev',
        enterIssueDescription: 'Sisesta probleemi kirjeldus',
        enterIssueAddress: 'Sisesta probleemi aadress',
        enterIssueReporter: 'Sisesta oma nimi',
        submitIssue: 'Estita tagasiside',
        successfullyUpdatedRideOrder: 'Tellimus edukalt uuendatud',
        successfullyCreatedANewRideOrder: 'Uus tellimus loodud',
        orderReceived: 'Tellimus kätte saadud',
        confirmationWillReceive: 'Kinnitus saadetud e-postile',
        placeNotFound: 'Kohta ei leitud'
    }
});

export default strings;